# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2cb0f4ee76d5f2968c8ebaf3534054fff95143ced58e682d436548740a10d7cc999f4f263ee7d1b911b7da38bafc7b537e7ed855b332e14cc5800640d252099

test:
  secret_key_base: 0714c53aad3983fd6ac700a4ab8f1c31d2a0e22fb2af384d1e5352c578869b7674c4f222622add588ab5ae19cf978df9a3bb0cc3b370e7bfad8f2d401fb57b74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
